name: Bug Report
description: Report a bug or issue
title: "[Bug] "
labels: ["external", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! This will be reviewed by our team and added to our backlog.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What's the bug?
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Minor inconvenience
        - Moderate impact
        - Major blocker
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or error messages?
      placeholder: Add any additional information...
    validations:
      required: false
