name: Feature Request
description: Submit a feature request or enhancement idea
title: "[Feature] "
labels: ["external", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request! This will be reviewed by our team and added to our backlog.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Describe the feature you'd like to request...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: This feature would help with...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature?
      placeholder: Describe your use case...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Perspective)
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples?
      placeholder: Add any additional information...
    validations:
      required: false
